server:
  port: 8888  # Porta onde o Config Server irá rodar

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seu-repositorio-config  # URL do seu repositório Git que armazenará as configurações
          clone-on-start: true  # Clonar o repositório ao iniciar o servidor
