server:
  port: 8888  

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seu-repo-de-config  
          clone-on-start: true  

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/  
  instance:
    prefer-ip-address: true
